### PR TITLE
enhance intellisense alot

### PR DESCRIPTION
**Pull request by reaby**
enhancing the intellisense autocomplete.

as well adds possibility to cast  context at beginning of file:
```
/** @context {type} */
```

### CODE REVIEW

**Comment by BigBang1112** [comment]
With Reaby, we've got an idea about the future of this extension.
I've contacted you MattMcFarland on Maniaplanet Forum about it.

**Comment by reaby** [comment]
Oh, i need to work with this, reident lines doesn't work yet right.

**Comment by MattMcFarland** [comment]
Very exciting!  We might need to update the CI of this to automate the release to VS marketplace.

**Comment by reaby** [comment]
Well this has still some issues, but it's definelty better than before...

**Pull request merged**
